export const AMBIENT_PHOTO_DURATION_MS = 240000;
export const AMBIENT_PHOTO_FADE_DURATION_MS = 3600;
export const AMBIENT_PHOTO_MOTION_DURATION_MS = 240000;
export const AMBIENT_PHOTO_MOTION_SCALE = 0.03;

export const AMBIENT_PHOTO_MIN_WIDTH = 2560;
export const AMBIENT_PHOTO_MIN_HEIGHT = 1440;
export const AMBIENT_PHOTO_MIN_ASPECT_RATIO = 1.45;
export const AMBIENT_PHOTO_MAX_ASPECT_RATIO = 2.4;
export const AMBIENT_PHOTO_MIN_MEGAPIXELS = 3.6;
